project_id          = "deepskin-451908"
region              = "europe-west1"
dataset_bucket_name = "deepskin_dataset"
model_bucket_name   = "trained_deepskin_model"
code_bucket_name    = "deepskin_code"
