name: Deploy on Google Run 

on:
  push:
    branches:
      - develop_front

jobs: 
  deploy-backend:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: deepskin-451908  
      REGION: europe-west1

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GC_CLEM }}

      - name: Configure gcloud
        run: |
          gcloud config set project $PROJECT_ID
          gcloud config set run/region $REGION

      - name: Build and push Docker image backend
        run: |
          docker build -f deployment/Dockerfile --platform linux/amd64 -t deepskin-backend .
          docker tag deepskin-backend europe-west1-docker.pkg.dev/deepskin-451908/deepskin/deepskin-backend
          gcloud auth configure-docker europe-west1-docker.pkg.dev
          docker push europe-west1-docker.pkg.dev/deepskin-451908/deepskin/deepskin-backend

      - name: Deploy backend to Cloud Run
        run: |
          gcloud run deploy deepskin-back \
            --image europe-west1-docker.pkg.dev/$PROJECT_ID/deepskin/deepskin-backend \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated \
            --port 5100 \
            --member="allUsers" \
            --memory 1Gi \
            --format json > backend_output.json

      - name: Extract Backend URL
        run: echo "BACKEND_URL=$(jq -r '.[0].status.url' backend_output.json)" >> $GITHUB_ENV

  deploy-frontend:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: deepskin-451908  
      REGION: europe-west1

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GC_CLEM }}

      - name: Build and push frontend image
        run: |
          docker build -f streamlit/Dockerfile --platform linux/amd64 -t deepskin-frontend .
          docker tag deepskin-frontend europe-west1-docker.pkg.dev/deepskin-451908/deepskin/deepskin-frontend
          gcloud auth configure-docker europe-west1-docker.pkg.dev
          docker push europe-west1-docker.pkg.dev/deepskin-451908/deepskin/deepskin-frontend

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy deepskin-front \
            --image europe-west1-docker.pkg.dev/$PROJECT_ID/deepskin/deepskin-frontend \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated \
            --member="allUsers" \
            --set-env-vars BACK_URL=${{ env.BACKEND_URL }} \
            --port 8501 