name: Deploy on Google Run 

on:
  pull_request:
    branches:
      - develop
      - main
      - pylint
      - pytest_local
  push: 
    branches:
      - develop
      - main
      - pylint
      - pytest_local

jobs: 
  pytest:
    uses: ./.github/workflows/pytest.yml
    with:
      BACKEND_URL: ${{ needs.deploy-backend.outputs.BACKEND_URL }}